name: AppImage
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Get linuxdeploy
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -O linuxdeploy.AppImage
          chmod +x linuxdeploy.AppImage
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
      - name: Build resources
        run: poetry run make runekit/_resources.py
      - name: Build AppImage
        run: LINUXDEPLOY=./linuxdeploy.AppImage make dist/RuneKit.AppImage

      # Deploy
      - name: Upload to CI
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: continuous
          prerelease: true
          name: Continuous Integration
          body: These files are automatically built with GitHub Actions from the main branch.
          files: |
            dist/RuneKit.AppImage
            dist/runekit.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to CI
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/RuneKit.AppImage
            dist/runekit.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
