name: Bump tags
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Bump tag
        if: github.ref == 'refs/heads/main'
        uses: richardsimko/update-tag@v1
        with:
          tag_name: continuous
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clear old releases
        uses: dev-drprasad/delete-tag-and-release@v1.1
        if: github.ref == 'refs/heads/main'
        with:
          delete_release: true
          tag_name: continuous
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
